# Generated by Django 4.2 on 2023-04-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingDate', models.DateField(auto_now_add=True)),
                ('generalDiscipline', models.CharField(choices=[('1 Point', '1 Point'), ('2 Points', '2 Points'), ('3 Points', '3 Points'), ('4 Points', '4 Points')], max_length=8)),
                ('workAptitudes', models.CharField(choices=[('1 Point', '1 Point'), ('2 Points', '2 Points'), ('3 Points', '3 Points'), ('4 Points', '4 Points')], max_length=8)),
                ('Initiative', models.CharField(choices=[('1 Point', '1 Point'), ('2 Points', '2 Points'), ('3 Points', '3 Points'), ('4 Points', '4 Points')], max_length=8)),
                ('innovationAbilities', models.CharField(choices=[('1 Point', '1 Point'), ('2 Points', '2 Points'), ('3 Points', '3 Points'), ('4 Points', '4 Points')], max_length=8)),
                ('knowledgeAcquired', models.CharField(choices=[('1 Point', '1 Point'), ('2 Points', '2 Points'), ('3 Points', '3 Points'), ('4 Points', '4 Points')], max_length=8)),
                ('totalGrade', models.CharField(max_length=2)),
                ('appreciation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internshipScheduledDay', models.DateField()),
                ('isPresent', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=200)),
                ('cardNumber', models.IntegerField()),
                ('ssn', models.IntegerField()),
                ('diploma', models.CharField(choices=[('Lisence', 'Lisence'), ('Master', 'Master')], max_length=7)),
                ('studentNumber', models.IntegerField()),
                ('theme', models.CharField(max_length=200)),
                ('offeredBy', models.CharField(max_length=200)),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('responsible', models.CharField(max_length=100)),
                ('responsibleEmail', models.CharField(max_length=100)),
                ('responsibleNumber', models.IntegerField()),
                ('supervisor', models.CharField(max_length=100)),
                ('supervisorEmail', models.CharField(max_length=100)),
                ('supervisorNumber', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Admin Accepted', 'Admin Accepted'), ('Accepted', 'Accepted')], max_length=14)),
                ('studentDep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('studentFac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisorName', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('InternshipSubject', models.CharField(max_length=200)),
                ('studentName', models.CharField(max_length=200)),
                ('internshipStartDate', models.DateField()),
                ('internshipEndDate', models.DateField()),
                ('certificateGivenDate', models.DateField(auto_now_add=True)),
                ('univName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.university')),
            ],
        ),
    ]
