# Generated by Django 4.2 on 2023-05-11 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birhtDate',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birhtPlace',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AddField(
            model_name='student',
            name='cardNumber',
            field=models.CharField(default='20XXXXXXXXXX', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ssn',
            field=models.CharField(default='XXXXXXXXXXXX', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='yearOfStudy',
            field=models.CharField(default='Lisence', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(max_length=12)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
