# Generated by Django 4.2 on 2023-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_birhtdate_remove_student_birhtplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='fax',
            field=models.CharField(max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='phoneNumber',
            field=models.CharField(default='+213000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='applications',
            field=models.ManyToManyField(
                blank=True, to='accounts.internshipapplication'),
        ),
        migrations.AddField(
            model_name='student',
            name='birthDate',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(default='+213000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='phoneNumber',
            field=models.CharField(default='+213000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='diploma',
            field=models.CharField(
                choices=[('Lisence', 'Lisence'), ('Master', 'Master')], max_length=7),
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
