# Generated by Django 4.2 on 2023-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_fax_admin_phonenumber_student_applications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='fax',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthPlace',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='fax',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
