# Generated by Django 4.2 on 2023-05-13 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_admin_fax_alter_student_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='applications',
        ),
        migrations.AddField(
            model_name='student',
            name='applications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.internshipapplication'),
        ),
    ]
