# Generated by Django 4.2 on 2023-05-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_remove_student_applications_student_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='applications',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
