# Generated by Django 4.2 on 2023-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_internshipoffer_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Admin Approved', 'Admin Approved'), ('Approved', 'Approved')], default='Pending', max_length=14),
        ),
    ]
